version: '3'
services: 
  app:
    build: .
    restart: always
    ports:
      - 5000:8080
  db:
    image: 'postgres'
    restart: always
    environment:
      - POSTGRES_PASSWORD=p
  adminer:
    image: adminer
    restart: always
    ports:
      - 5001:8080
  volumes:
    - /var/jenkins_home
    - /var/run/docker.sock:/var/run/docker.sock
