version: "3"
services: 
  adminer: 
    image: adminer
    ports: 
      - "5001:8080"
    restart: always
  app: 
    build: "."
    ports: 
      - "5000:8080"
    restart: always
  db: 
    environment: 
      - POSTGRES_PASSWORD=p
    image: postgres
    restart: always
volumes: 
  - /var/jenkins_home
  - "/var/run/docker.sock:/var/run/docker.sock"
